repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: [-s, soweego/cli.py]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [-i, -r, --remove-all-unused-imports, --remove-unused-variables]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [-S, -l 80]
