# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
conda:
  environment: .conda.yaml
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
formats:
  - epub
  - htmlzip
