dist: xenial
language: python
python: 3.7
script:
    - isort -y -rc soweego
    - autoflake -i -r --remove-all-unused-imports --remove-unused-variables soweego
    - black -S -l 80 soweego
    - git config --global user.name "travis"
    - git config --global user.email "travis@soweego.eqiad.wmflabs"
    - git config --global push.default simple
    - git checkout travis
    - git commit -am "format code & organize imports"
    - git push --quiet

