dist: xenial
language: python
install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -q -f .conda.yml
  - conda activate soweego
script:
    - isort -s soweego/cli.py soweego
    - autoflake -i -r --remove-all-unused-imports --remove-unused-variables soweego
    - black -S -l 80 soweego
    - |
        if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
            git config --global user.name "travis"
            git config --global user.email "travis@soweego"
            git config --global push.default simple
            git checkout -B $TRAVIS_PULL_REQUEST_BRANCH
            git commit -am "format code & organize imports"
            git pull --quiet origin $TRAVIS_PULL_REQUEST_BRANCH
            git push --quiet --set-upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/Wikidata/soweego $TRAVIS_PULL_REQUEST_BRANCH
        fi

