dist: xenial
language: python
python: "3.7"
script:
    - isort -y -rc soweego
    - autoflake -i -r --remove-all-unused-imports --remove-unused-variables soweego
    - black -S -l 80 soweego
    - flake8 --max-line-length 80 --max-complexity 10 soweego

